// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CostInstanceStatus.
const (
	DELETED      CostInstanceStatus = "DELETED"
	DELETING     CostInstanceStatus = "DELETING"
	ERROR        CostInstanceStatus = "ERROR"
	PROVISIONING CostInstanceStatus = "PROVISIONING"
	READY        CostInstanceStatus = "READY"
)

// Valid indicates whether the value is a known member of the CostInstanceStatus enum.
func (e CostInstanceStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case DELETING:
		return true
	case ERROR:
		return true
	case PROVISIONING:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for CostModelSpecDistribution.
const (
	CostModelSpecDistributionCpu    CostModelSpecDistribution = "cpu"
	CostModelSpecDistributionMemory CostModelSpecDistribution = "memory"
)

// Valid indicates whether the value is a known member of the CostModelSpecDistribution enum.
func (e CostModelSpecDistribution) Valid() bool {
	switch e {
	case CostModelSpecDistributionCpu:
		return true
	case CostModelSpecDistributionMemory:
		return true
	default:
		return false
	}
}

// Defines values for CostSpecServiceType.
const (
	Cost CostSpecServiceType = "cost"
)

// Valid indicates whether the value is a known member of the CostSpecServiceType enum.
func (e CostSpecServiceType) Valid() bool {
	switch e {
	case Cost:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ALREADYEXISTS       ErrorType = "ALREADY_EXISTS"
	BADGATEWAY          ErrorType = "BAD_GATEWAY"
	INTERNAL            ErrorType = "INTERNAL"
	INVALIDARGUMENT     ErrorType = "INVALID_ARGUMENT"
	NOTFOUND            ErrorType = "NOT_FOUND"
	PERMISSIONDENIED    ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED     ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE         ErrorType = "UNAVAILABLE"
	UNPROCESSABLEENTITY ErrorType = "UNPROCESSABLE_ENTITY"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case BADGATEWAY:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	case UNPROCESSABLEENTITY:
		return true
	default:
		return false
	}
}

// Defines values for MarkupUnit.
const (
	Percent MarkupUnit = "percent"
)

// Valid indicates whether the value is a known member of the MarkupUnit enum.
func (e MarkupUnit) Valid() bool {
	switch e {
	case Percent:
		return true
	default:
		return false
	}
}

// Defines values for RateCostType.
const (
	Infrastructure RateCostType = "Infrastructure"
	Supplementary  RateCostType = "Supplementary"
)

// Valid indicates whether the value is a known member of the RateCostType enum.
func (e RateCostType) Valid() bool {
	switch e {
	case Infrastructure:
		return true
	case Supplementary:
		return true
	default:
		return false
	}
}

// Defines values for RateMetric.
const (
	ClusterCostPerMonth      RateMetric = "cluster_cost_per_month"
	CpuCoreRequestPerHour    RateMetric = "cpu_core_request_per_hour"
	CpuCoreUsagePerHour      RateMetric = "cpu_core_usage_per_hour"
	MemoryGbRequestPerHour   RateMetric = "memory_gb_request_per_hour"
	MemoryGbUsagePerHour     RateMetric = "memory_gb_usage_per_hour"
	NodeCostPerMonth         RateMetric = "node_cost_per_month"
	PvcCostPerMonth          RateMetric = "pvc_cost_per_month"
	StorageGbRequestPerMonth RateMetric = "storage_gb_request_per_month"
	StorageGbUsagePerMonth   RateMetric = "storage_gb_usage_per_month"
)

// Valid indicates whether the value is a known member of the RateMetric enum.
func (e RateMetric) Valid() bool {
	switch e {
	case ClusterCostPerMonth:
		return true
	case CpuCoreRequestPerHour:
		return true
	case CpuCoreUsagePerHour:
		return true
	case MemoryGbRequestPerHour:
		return true
	case MemoryGbUsagePerHour:
		return true
	case NodeCostPerMonth:
		return true
	case PvcCostPerMonth:
		return true
	case StorageGbRequestPerMonth:
		return true
	case StorageGbUsagePerMonth:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageParamsMetric.
const (
	GetUsageParamsMetricCompute GetUsageParamsMetric = "compute"
	GetUsageParamsMetricMemory  GetUsageParamsMetric = "memory"
	GetUsageParamsMetricStorage GetUsageParamsMetric = "storage"
)

// Valid indicates whether the value is a known member of the GetUsageParamsMetric enum.
func (e GetUsageParamsMetric) Valid() bool {
	switch e {
	case GetUsageParamsMetricCompute:
		return true
	case GetUsageParamsMetricMemory:
		return true
	case GetUsageParamsMetricStorage:
		return true
	default:
		return false
	}
}

// CostInstance A cost visibility instance backed by Koku
type CostInstance struct {
	// ClusterId Resolved OpenShift cluster ID (from ClusterVersion)
	ClusterId *string `json:"cluster_id,omitempty"`

	// CreateTime Creation timestamp
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM-level resource identifier.
	Id *string `json:"id,omitempty"`

	// Path Resource path
	Path *string `json:"path,omitempty"`

	// Spec Cost instance specification
	Spec CostSpec `json:"spec"`

	// Status Current status
	Status *CostInstanceStatus `json:"status,omitempty"`

	// StatusMessage Human-readable status message
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Last update timestamp
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// CostInstanceStatus Current status
type CostInstanceStatus string

// CostInstanceList Paginated list of cost instances
type CostInstanceList struct {
	Instances *[]CostInstance `json:"instances,omitempty"`

	// NextPageToken Token for next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// CostMetadata Resource metadata
type CostMetadata struct {
	// Labels Key-value labels
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`
}

// CostModelSpec Cost model configuration
type CostModelSpec struct {
	// Distribution Overhead distribution strategy
	Distribution *CostModelSpecDistribution `json:"distribution,omitempty"`

	// Markup Markup percentage
	Markup *Markup `json:"markup,omitempty"`

	// Rates Rate definitions (omit for Tier 2 distribution-only)
	Rates *[]Rate `json:"rates,omitempty"`
}

// CostModelSpecDistribution Overhead distribution strategy
type CostModelSpecDistribution string

// CostSpec Cost instance specification
type CostSpec struct {
	// CostModel Cost model configuration
	CostModel *CostModelSpec `json:"cost_model,omitempty"`

	// Currency ISO 4217 currency code
	Currency *string `json:"currency,omitempty"`

	// Metadata Resource metadata
	Metadata CostMetadata `json:"metadata"`

	// ServiceType Must be "cost"
	ServiceType CostSpecServiceType `json:"service_type"`

	// Target Reference to the target resource
	Target CostTarget `json:"target"`
}

// CostSpecServiceType Must be "cost"
type CostSpecServiceType string

// CostTarget Reference to the target resource
type CostTarget struct {
	// ResourceId DCM cluster instance ID
	ResourceId string `json:"resource_id"`

	// ResourceType Target resource type
	ResourceType *string `json:"resource_type,omitempty"`
}

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string   `json:"detail,omitempty"`
	Instance *string   `json:"instance,omitempty"`
	Status   *int32    `json:"status,omitempty"`
	Title    string    `json:"title"`
	Type     ErrorType `json:"type"`
}

// ErrorType defines model for Error.Type.
type ErrorType string

// Health Health status singleton
type Health struct {
	Path    *string `json:"path,omitempty"`
	Status  *string `json:"status,omitempty"`
	Type    *string `json:"type,omitempty"`
	Uptime  *int    `json:"uptime,omitempty"`
	Version *string `json:"version,omitempty"`
}

// Markup Markup percentage
type Markup struct {
	Unit MarkupUnit `json:"unit"`

	// Value Markup value
	Value float64 `json:"value"`
}

// MarkupUnit defines model for Markup.Unit.
type MarkupUnit string

// Rate A single cost rate
type Rate struct {
	// CostType Cost classification
	CostType *RateCostType `json:"cost_type,omitempty"`

	// Metric Koku-compatible metric name
	Metric RateMetric `json:"metric"`

	// Value Rate value
	Value float64 `json:"value"`
}

// RateCostType Cost classification
type RateCostType string

// RateMetric Koku-compatible metric name
type RateMetric string

// InstanceIdPath defines model for InstanceIdPath.
type InstanceIdPath = string

// ListInstancesParams defines parameters for ListInstances.
type ListInstancesParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateInstanceParams defines parameters for CreateInstance.
type CreateInstanceParams struct {
	// Id Client-assigned resource identifier (AEP-133). If omitted, the server generates a UUID.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetCostReportParams defines parameters for GetCostReport.
type GetCostReportParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUsageParamsMetric defines parameters for GetUsage.
type GetUsageParamsMetric string

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CostInstance

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all cost instances
	// (GET /api/v1alpha1/instances)
	ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams)
	// Create a new cost instance
	// (POST /api/v1alpha1/instances)
	CreateInstance(w http.ResponseWriter, r *http.Request, params CreateInstanceParams)
	// Health check
	// (GET /api/v1alpha1/instances/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Delete a cost instance
	// (DELETE /api/v1alpha1/instances/{instanceId})
	DeleteInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath)
	// Get cost instance details
	// (GET /api/v1alpha1/instances/{instanceId})
	GetInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath)
	// Get cost report for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/cost-reports)
	GetCostReport(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, params GetCostReportParams)
	// Get cost forecast for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/cost-reports/forecast)
	GetCostForecast(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath)
	// Get usage data for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/usage/{metric})
	GetUsage(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, metric GetUsageParamsMetric, params GetUsageParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all cost instances
// (GET /api/v1alpha1/instances)
func (_ Unimplemented) ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new cost instance
// (POST /api/v1alpha1/instances)
func (_ Unimplemented) CreateInstance(w http.ResponseWriter, r *http.Request, params CreateInstanceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /api/v1alpha1/instances/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a cost instance
// (DELETE /api/v1alpha1/instances/{instanceId})
func (_ Unimplemented) DeleteInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cost instance details
// (GET /api/v1alpha1/instances/{instanceId})
func (_ Unimplemented) GetInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cost report for a cost instance
// (GET /api/v1alpha1/instances/{instanceId}/cost-reports)
func (_ Unimplemented) GetCostReport(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, params GetCostReportParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get cost forecast for a cost instance
// (GET /api/v1alpha1/instances/{instanceId}/cost-reports/forecast)
func (_ Unimplemented) GetCostForecast(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get usage data for a cost instance
// (GET /api/v1alpha1/instances/{instanceId}/usage/{metric})
func (_ Unimplemented) GetUsage(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, metric GetUsageParamsMetric, params GetUsageParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstancesParams

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInstances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInstance operation middleware
func (siw *ServerInterfaceWrapper) CreateInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateInstanceParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInstance(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInstance operation middleware
func (siw *ServerInterfaceWrapper) DeleteInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceId" -------------
	var instanceId InstanceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "instanceId", chi.URLParam(r, "instanceId"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInstance(w, r, instanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceId" -------------
	var instanceId InstanceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "instanceId", chi.URLParam(r, "instanceId"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInstance(w, r, instanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCostReport operation middleware
func (siw *ServerInterfaceWrapper) GetCostReport(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceId" -------------
	var instanceId InstanceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "instanceId", chi.URLParam(r, "instanceId"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCostReportParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_date", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_date", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCostReport(w, r, instanceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCostForecast operation middleware
func (siw *ServerInterfaceWrapper) GetCostForecast(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceId" -------------
	var instanceId InstanceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "instanceId", chi.URLParam(r, "instanceId"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCostForecast(w, r, instanceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsage operation middleware
func (siw *ServerInterfaceWrapper) GetUsage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceId" -------------
	var instanceId InstanceIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "instanceId", chi.URLParam(r, "instanceId"), &instanceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceId", Err: err})
		return
	}

	// ------------- Path parameter "metric" -------------
	var metric GetUsageParamsMetric

	err = runtime.BindStyledParameterWithOptions("simple", "metric", chi.URLParam(r, "metric"), &metric, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "metric", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsageParams

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_date", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_date", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsage(w, r, instanceId, metric, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances", wrapper.ListInstances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1alpha1/instances", wrapper.CreateInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1alpha1/instances/{instanceId}", wrapper.DeleteInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances/{instanceId}", wrapper.GetInstance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances/{instanceId}/cost-reports", wrapper.GetCostReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances/{instanceId}/cost-reports/forecast", wrapper.GetCostForecast)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1alpha1/instances/{instanceId}/usage/{metric}", wrapper.GetUsage)
	})

	return r
}

type ListInstancesRequestObject struct {
	Params ListInstancesParams
}

type ListInstancesResponseObject interface {
	VisitListInstancesResponse(w http.ResponseWriter) error
}

type ListInstances200JSONResponse CostInstanceList

func (response ListInstances200JSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances400ApplicationProblemPlusJSONResponse Error

func (response ListInstances400ApplicationProblemPlusJSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListInstances500ApplicationProblemPlusJSONResponse Error

func (response ListInstances500ApplicationProblemPlusJSONResponse) VisitListInstancesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstanceRequestObject struct {
	Params CreateInstanceParams
	Body   *CreateInstanceJSONRequestBody
}

type CreateInstanceResponseObject interface {
	VisitCreateInstanceResponse(w http.ResponseWriter) error
}

type CreateInstance201JSONResponse CostInstance

func (response CreateInstance201JSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance400ApplicationProblemPlusJSONResponse Error

func (response CreateInstance400ApplicationProblemPlusJSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance409ApplicationProblemPlusJSONResponse Error

func (response CreateInstance409ApplicationProblemPlusJSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance422ApplicationProblemPlusJSONResponse Error

func (response CreateInstance422ApplicationProblemPlusJSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInstance500ApplicationProblemPlusJSONResponse Error

func (response CreateInstance500ApplicationProblemPlusJSONResponse) VisitCreateInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstanceRequestObject struct {
	InstanceId InstanceIdPath `json:"instanceId"`
}

type DeleteInstanceResponseObject interface {
	VisitDeleteInstanceResponse(w http.ResponseWriter) error
}

type DeleteInstance204Response struct {
}

func (response DeleteInstance204Response) VisitDeleteInstanceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteInstance404ApplicationProblemPlusJSONResponse Error

func (response DeleteInstance404ApplicationProblemPlusJSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteInstance500ApplicationProblemPlusJSONResponse Error

func (response DeleteInstance500ApplicationProblemPlusJSONResponse) VisitDeleteInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstanceRequestObject struct {
	InstanceId InstanceIdPath `json:"instanceId"`
}

type GetInstanceResponseObject interface {
	VisitGetInstanceResponse(w http.ResponseWriter) error
}

type GetInstance200JSONResponse CostInstance

func (response GetInstance200JSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance404ApplicationProblemPlusJSONResponse Error

func (response GetInstance404ApplicationProblemPlusJSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetInstance500ApplicationProblemPlusJSONResponse Error

func (response GetInstance500ApplicationProblemPlusJSONResponse) VisitGetInstanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostReportRequestObject struct {
	InstanceId InstanceIdPath `json:"instanceId"`
	Params     GetCostReportParams
}

type GetCostReportResponseObject interface {
	VisitGetCostReportResponse(w http.ResponseWriter) error
}

type GetCostReport200JSONResponse map[string]interface{}

func (response GetCostReport200JSONResponse) VisitGetCostReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostReport404ApplicationProblemPlusJSONResponse Error

func (response GetCostReport404ApplicationProblemPlusJSONResponse) VisitGetCostReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostReport500ApplicationProblemPlusJSONResponse Error

func (response GetCostReport500ApplicationProblemPlusJSONResponse) VisitGetCostReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostReport502ApplicationProblemPlusJSONResponse Error

func (response GetCostReport502ApplicationProblemPlusJSONResponse) VisitGetCostReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostForecastRequestObject struct {
	InstanceId InstanceIdPath `json:"instanceId"`
}

type GetCostForecastResponseObject interface {
	VisitGetCostForecastResponse(w http.ResponseWriter) error
}

type GetCostForecast200JSONResponse map[string]interface{}

func (response GetCostForecast200JSONResponse) VisitGetCostForecastResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostForecast404ApplicationProblemPlusJSONResponse Error

func (response GetCostForecast404ApplicationProblemPlusJSONResponse) VisitGetCostForecastResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostForecast500ApplicationProblemPlusJSONResponse Error

func (response GetCostForecast500ApplicationProblemPlusJSONResponse) VisitGetCostForecastResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetCostForecast502ApplicationProblemPlusJSONResponse Error

func (response GetCostForecast502ApplicationProblemPlusJSONResponse) VisitGetCostForecastResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsageRequestObject struct {
	InstanceId InstanceIdPath       `json:"instanceId"`
	Metric     GetUsageParamsMetric `json:"metric"`
	Params     GetUsageParams
}

type GetUsageResponseObject interface {
	VisitGetUsageResponse(w http.ResponseWriter) error
}

type GetUsage200JSONResponse map[string]interface{}

func (response GetUsage200JSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsage404ApplicationProblemPlusJSONResponse Error

func (response GetUsage404ApplicationProblemPlusJSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsage500ApplicationProblemPlusJSONResponse Error

func (response GetUsage500ApplicationProblemPlusJSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetUsage502ApplicationProblemPlusJSONResponse Error

func (response GetUsage502ApplicationProblemPlusJSONResponse) VisitGetUsageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all cost instances
	// (GET /api/v1alpha1/instances)
	ListInstances(ctx context.Context, request ListInstancesRequestObject) (ListInstancesResponseObject, error)
	// Create a new cost instance
	// (POST /api/v1alpha1/instances)
	CreateInstance(ctx context.Context, request CreateInstanceRequestObject) (CreateInstanceResponseObject, error)
	// Health check
	// (GET /api/v1alpha1/instances/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Delete a cost instance
	// (DELETE /api/v1alpha1/instances/{instanceId})
	DeleteInstance(ctx context.Context, request DeleteInstanceRequestObject) (DeleteInstanceResponseObject, error)
	// Get cost instance details
	// (GET /api/v1alpha1/instances/{instanceId})
	GetInstance(ctx context.Context, request GetInstanceRequestObject) (GetInstanceResponseObject, error)
	// Get cost report for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/cost-reports)
	GetCostReport(ctx context.Context, request GetCostReportRequestObject) (GetCostReportResponseObject, error)
	// Get cost forecast for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/cost-reports/forecast)
	GetCostForecast(ctx context.Context, request GetCostForecastRequestObject) (GetCostForecastResponseObject, error)
	// Get usage data for a cost instance
	// (GET /api/v1alpha1/instances/{instanceId}/usage/{metric})
	GetUsage(ctx context.Context, request GetUsageRequestObject) (GetUsageResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListInstances operation middleware
func (sh *strictHandler) ListInstances(w http.ResponseWriter, r *http.Request, params ListInstancesParams) {
	var request ListInstancesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInstances(ctx, request.(ListInstancesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInstances")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInstancesResponseObject); ok {
		if err := validResponse.VisitListInstancesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInstance operation middleware
func (sh *strictHandler) CreateInstance(w http.ResponseWriter, r *http.Request, params CreateInstanceParams) {
	var request CreateInstanceRequestObject

	request.Params = params

	var body CreateInstanceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInstance(ctx, request.(CreateInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInstanceResponseObject); ok {
		if err := validResponse.VisitCreateInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInstance operation middleware
func (sh *strictHandler) DeleteInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	var request DeleteInstanceRequestObject

	request.InstanceId = instanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInstance(ctx, request.(DeleteInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteInstanceResponseObject); ok {
		if err := validResponse.VisitDeleteInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInstance operation middleware
func (sh *strictHandler) GetInstance(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	var request GetInstanceRequestObject

	request.InstanceId = instanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInstance(ctx, request.(GetInstanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInstance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInstanceResponseObject); ok {
		if err := validResponse.VisitGetInstanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCostReport operation middleware
func (sh *strictHandler) GetCostReport(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, params GetCostReportParams) {
	var request GetCostReportRequestObject

	request.InstanceId = instanceId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCostReport(ctx, request.(GetCostReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCostReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCostReportResponseObject); ok {
		if err := validResponse.VisitGetCostReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCostForecast operation middleware
func (sh *strictHandler) GetCostForecast(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath) {
	var request GetCostForecastRequestObject

	request.InstanceId = instanceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCostForecast(ctx, request.(GetCostForecastRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCostForecast")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCostForecastResponseObject); ok {
		if err := validResponse.VisitGetCostForecastResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUsage operation middleware
func (sh *strictHandler) GetUsage(w http.ResponseWriter, r *http.Request, instanceId InstanceIdPath, metric GetUsageParamsMetric, params GetUsageParams) {
	var request GetUsageRequestObject

	request.InstanceId = instanceId
	request.Metric = metric
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUsage(ctx, request.(GetUsageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUsage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUsageResponseObject); ok {
		if err := validResponse.VisitGetUsageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
