// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbb3PbNtL/Khi0L+w8lGQnaftU9+JGtdREU1v2SHLuepFPA5MrCQ0JsADoWPXou98s",
	"QJCUSNlK06TtTN5ZBLBY7J/f/rCkH2gok1QKEEbT7gNNmWIJGFD211Bow0QIw+iKmRU+iUCHiqeGS0G7",
	"tH920YrhDmISSm0Iz6cTBVpmKgTCIxCGLzgoGlCOS1IUFFDBEqBdyosNaEAV/JpxBRHtGpVBQHW4goQ5",
	"rYwBhcv/+5a1fjtpfX9zlP/Runk4Cb493fjnx//8mgbUrFMUr43iYkk3m42XZo91JrXxR6sfqucOc8c1",
	"v+UxN+vyXLcsfAcRuV2Tn+S7jAY0VTIFZThYuWGcaQNqzqO61DFoGd9BRC5TEJMVXxiSTyfDPjlaKJmQ",
	"M/fgDSjNpTi2JmHRpYjX3iQ75wpoqIAZmBueNJzkDAe5FASHtWFJSgO6kCphhnZpxAy07MID9mk6Uun9",
	"Bn+30TpNbmvlfz3b9tiTGqSNETj2O+dx9aQYnUKIYr5WsKBd+lWnjP9OHiIdjI8JzsP5hplMN9g2UwqE",
	"Ifl4QEFkCe2+pVfjyzfDyfByNBy9ogEdD3r9n2lAB+Px5ZgGtD84H0zdkP1z0Kc3h6htt5knoDVbNrj6",
	"dZYw0UIx7DaGXCvipx+wQZZG+wPpnGlD3IyPjqVNNdHfOn/cFLPk7S8QGhrQ+xaDtOUDqwICGlf5jNSd",
	"B//nBqWkcaZYXAEW9IzmYpnFTFUelxDxTr7LWpjwrVTJOx6Bakdh0uayU8xFlauQcc61qdvoii25YAYi",
	"EnNtiFxsY6KuoUU5gj8MJPqQuCxwa1McgSnF1vhbwL2Zp2wJcyPfgajrOMXHZCEVwakkdbFRd9C2M/Lj",
	"X4BhETPskSRM/JTds8bsFmL7F4sijstYfLU1oxaQ21v8BOvWHYszILmoBiVdTXkiM+ykgCbs/hzEEiHl",
	"2xcBTbjwP08/DLcej267280+g8oI4kmORzvogqGT4DgJpVjwZaYsktcMG3Hc+TZz61DMgmUxpmSYYoHa",
	"Fnt5B2oFLCLVZUQbxQws1xUQc4sTSKRaV/QvvZMw9S5LnwrYCzcLjcIMNKDoGBElggUXNig0OZIJNzZC",
	"pxwUeb6laUuKeI1l8aBsQdn1LNkX3Y/4oSj/iFV8wcNmV2C6z63PDsnj0vlYxW0xCdfbHrye9GseHE4u",
	"ycvnp98Rv4SEMoKdWttr/efm4cWmITzRp2UWP6mjn4sFCNQdD2HuBO7a6SLThtwCmVkrzGg1lKQ2jSFk",
	"mFqCOUSPqZtZKx1VlSonK0TvS7xpsfMuji0AjQrESGJWQJycgt7UXO4H5nvoUUHxihAa9pucUsgprVuk",
	"sZNQC4TptmokN8LjcFTVt8k4A6WkarDLj2fku/8/+Y6gf2LOhCGAM3H3VApdN0wEhvG4Edd5hXgX/CFT",
	"vKW89ele/rO1hgvz4nk5lwsDS1A2sriJoXFzb18fnMPRm975sD/vjV9dXwxGUxrQ0eV0/uPl9Qgd1Tu3",
	"9G0++PdwMp3QgF4NxhfDCbK7eX8wGg5w0vWodz19PRhNh2e9qX0yHE0H41Hv3A2+6Q3Pez+cD+yvq/Hl",
	"2WAywd9zXDJFbvhDrz9/1ZsO/tX7Gd1yqFV2nOsjwB6+ybuvgcVNHNo995wR2VIMpgHgPAM/kKweNNU7",
	"ZO+ZDyCunrPumVoJjDt3szpAs2bbFmQ/v214eYUWH0xkV84nVerqHnni6lzhb8Qlk80XHsBj85l4pIui",
	"au/At31OUlAhCONY4bbvM8FNNXHyqY3Abnna3k3caPXuILPb2AI4FzxB8SeFUJElt+i6HXd4GVarplC3",
	"tb/hZu8s6pg5UpLmIl5H4aFYKKaNykKTKaiBsaUJYcy0rtKDAmR2F0+yNI0hQVPvo1dgFG/gIz85Lycp",
	"MxzZrJvnSW2Fvc1DqWCe4e1vnoKar2SGNaQYQWuCNtUxx/bmy9v6snKoYZ02UuH8rYWJFDY6K4PVpX5Y",
	"yAjm1ubVp76PUhtI78Ldhx8QgJZs/hHhl3vHb1QPwI2tcwvpIkoYFtrkyZteSAyulMzxIVM26Y1JdbfT",
	"WXKzym7boUw6UZhgLvuQ3j7LxHEf4pOd9K6GljYnTOBFdLm3iaXLLtZMjCEir5kh53y5MjoFiIiN5QuU",
	"YiOUHOWq2pbXcXsmZmK64tpuyDVJmbKXXaRLfc/VUUwss2hLTv/s4pjkByJMRF53PRO248jFMnBaWxId",
	"2DnhCnkOakxCljJ7Fg7aHrXWSdNWu6++ImjhMSy5vdngFccz2ZlokWfPRiyB7rNnpI6Zbjw37nSd2mmW",
	"0tqByxScQI3Pz8aD3nQQENfHCQhyhRkmfsxDQFZUuryXsnAF5Hn7pObx9+/ft5kdbku17ORrded8eDYY",
	"TQYtXFNyGosAzkc+BK4qIVCpSV162j5xa2UKgqWcdumL9kn7ZV6/LN51WMo7d6csTlfstLPVkthDkU2m",
	"hCaMpLV+B4t3+sDaRaPrmBoMGr0Ttm1qtXNGHUa0S8952eNwlbZsSL/d389YgAlXGPYYh0VzA7VSoLPY",
	"aN9//jUDtS4b0JVuSbXhXGMD9WJ2j2BBHEJU9sGrg7JGwnLqWyxNWyfs3jVrNP8NtnYv6s43J0Gd7yZu",
	"a9o9PTmpoNZpnfBsbGfRUXTr0ucnJx6SsHh3HyhL0zivWJ1ftKNGpSKHNqNsR8yi3k7fsLkTtgnoy0c1",
	"SZW8jSH5vw/TyN1eGtQYijsW84jkFQj3/+bz7o98j8U2/EG5y5OtKjpLEuQAuanqGWQvs0vtaIR/drMJ",
	"aCqbmpC24w+YnnvfYWC2MFEHzzaZroBMrmZCWeQEhWIs3ORXzCMEZJm67l289ptYtD62css780wUYou3",
	"EFwTptciXCkpZKb/4SABRJRKLkyeNZrwJIGIMwPxeibec7Mi1ZZ6fk1x2haHMooJnbeQjLRI/DOROIIH",
	"wCOFwO9AE240WXCFauc1h2BdaFvc3kYiZ8th2TF+FIrOYg7CtJACLgVETa9EyFFvcNU6ffHiuE2GCyIT",
	"bgxEgbVaHhlLEKByD15fD/vtPdjBI/qHvh+7cQQHtPlBRutPghEuMbbf8W1q+HT6Cfd+rLUXFkEquMHg",
	"i/4KKPXy5PvPuX9uCxbj5XhN4J5ro/PE5jrPbKvX8+efT6+80+VbaUIiVKB+0v1YyExEf0lMdwhCGBHw",
	"fhvX98D6JthHyPwt/ilehliy2urn5Nz8aeb1Csxr31T4ZKzhtW9G1Ay61YXaMWQ+Fq4gfFcxXS7sUbs9",
	"lJ8YbJzZYmjqDVyxTIOzX7XmYclTkMi7fKyseOSILwgT6+M23i5sKZmJFccL79pejBTY0IhcqXJ3Rk2c",
	"zaXCKaPLaS48IkfcEK6LstnSoUwhsvsnbO2ijEizAkVCKXSWgNLHTWWrbw+4v2w1eaec0tn55KOBQr58",
	"6jWJNXEDlr78E7Dsrw0QzleeSD0BDsHTme/a7jbnWfG2aufbHI4hFiHxQS4Ubn3G0AgKnzCUTv6kap/b",
	"6UtYNoflKyy3jQb74LJVhd+ObbUoSKUy+zsMV0rec9B5j9ZOJsh+8ZmRFpwDx/djZvyNv392USg7E8O+",
	"f4HH0lTJVCEIFQRiwWO8lzRA5yswGCdju+lHh3vw0EjdtWHKzCPXfC6dufUpTdO7nmZpIKIPl/Wxidj8",
	"DcfWe5RqJ7QhE3O/4tWL2E/f7Pd0X9LRpyNq8RkptmU8WaqNApY8Dgm552wXYW/ZKrPo98JDZyEVhMz1",
	"OJ7GCT97FykeyfIf/QZ/dln7+GwqTv8ln/52+VT47lNklH0f13lwd4/Nk6lkp39YsSW21s7E7yq21/nH",
	"qR9dZ7ePY8X6V6NGEl8yG74/L97k7f/2vPyOKUkzA+VnccXLzYZ3kF+KfzNcOdd8gam/E0xlFZ89ilEu",
	"nW/cf1vYczU1ysdSlq+9O7Z85gIe7yrEfAHhOoyBFDiiy1QYVl4uPewPulTJ+zU5sgfPmcZxKcQdoC6g",
	"Slkfl1CF6bqcahur8RS+O3az+V8AAAD//7hT9/2YMwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
