// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CostInstanceStatus.
const (
	DELETED      CostInstanceStatus = "DELETED"
	DELETING     CostInstanceStatus = "DELETING"
	ERROR        CostInstanceStatus = "ERROR"
	PROVISIONING CostInstanceStatus = "PROVISIONING"
	READY        CostInstanceStatus = "READY"
)

// Valid indicates whether the value is a known member of the CostInstanceStatus enum.
func (e CostInstanceStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case DELETING:
		return true
	case ERROR:
		return true
	case PROVISIONING:
		return true
	case READY:
		return true
	default:
		return false
	}
}

// Defines values for CostModelSpecDistribution.
const (
	CostModelSpecDistributionCpu    CostModelSpecDistribution = "cpu"
	CostModelSpecDistributionMemory CostModelSpecDistribution = "memory"
)

// Valid indicates whether the value is a known member of the CostModelSpecDistribution enum.
func (e CostModelSpecDistribution) Valid() bool {
	switch e {
	case CostModelSpecDistributionCpu:
		return true
	case CostModelSpecDistributionMemory:
		return true
	default:
		return false
	}
}

// Defines values for CostSpecServiceType.
const (
	Cost CostSpecServiceType = "cost"
)

// Valid indicates whether the value is a known member of the CostSpecServiceType enum.
func (e CostSpecServiceType) Valid() bool {
	switch e {
	case Cost:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	ALREADYEXISTS       ErrorType = "ALREADY_EXISTS"
	BADGATEWAY          ErrorType = "BAD_GATEWAY"
	INTERNAL            ErrorType = "INTERNAL"
	INVALIDARGUMENT     ErrorType = "INVALID_ARGUMENT"
	NOTFOUND            ErrorType = "NOT_FOUND"
	PERMISSIONDENIED    ErrorType = "PERMISSION_DENIED"
	UNAUTHENTICATED     ErrorType = "UNAUTHENTICATED"
	UNAVAILABLE         ErrorType = "UNAVAILABLE"
	UNPROCESSABLEENTITY ErrorType = "UNPROCESSABLE_ENTITY"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case ALREADYEXISTS:
		return true
	case BADGATEWAY:
		return true
	case INTERNAL:
		return true
	case INVALIDARGUMENT:
		return true
	case NOTFOUND:
		return true
	case PERMISSIONDENIED:
		return true
	case UNAUTHENTICATED:
		return true
	case UNAVAILABLE:
		return true
	case UNPROCESSABLEENTITY:
		return true
	default:
		return false
	}
}

// Defines values for MarkupUnit.
const (
	Percent MarkupUnit = "percent"
)

// Valid indicates whether the value is a known member of the MarkupUnit enum.
func (e MarkupUnit) Valid() bool {
	switch e {
	case Percent:
		return true
	default:
		return false
	}
}

// Defines values for RateCostType.
const (
	Infrastructure RateCostType = "Infrastructure"
	Supplementary  RateCostType = "Supplementary"
)

// Valid indicates whether the value is a known member of the RateCostType enum.
func (e RateCostType) Valid() bool {
	switch e {
	case Infrastructure:
		return true
	case Supplementary:
		return true
	default:
		return false
	}
}

// Defines values for RateMetric.
const (
	ClusterCostPerMonth      RateMetric = "cluster_cost_per_month"
	CpuCoreRequestPerHour    RateMetric = "cpu_core_request_per_hour"
	CpuCoreUsagePerHour      RateMetric = "cpu_core_usage_per_hour"
	MemoryGbRequestPerHour   RateMetric = "memory_gb_request_per_hour"
	MemoryGbUsagePerHour     RateMetric = "memory_gb_usage_per_hour"
	NodeCostPerMonth         RateMetric = "node_cost_per_month"
	PvcCostPerMonth          RateMetric = "pvc_cost_per_month"
	StorageGbRequestPerMonth RateMetric = "storage_gb_request_per_month"
	StorageGbUsagePerMonth   RateMetric = "storage_gb_usage_per_month"
)

// Valid indicates whether the value is a known member of the RateMetric enum.
func (e RateMetric) Valid() bool {
	switch e {
	case ClusterCostPerMonth:
		return true
	case CpuCoreRequestPerHour:
		return true
	case CpuCoreUsagePerHour:
		return true
	case MemoryGbRequestPerHour:
		return true
	case MemoryGbUsagePerHour:
		return true
	case NodeCostPerMonth:
		return true
	case PvcCostPerMonth:
		return true
	case StorageGbRequestPerMonth:
		return true
	case StorageGbUsagePerMonth:
		return true
	default:
		return false
	}
}

// Defines values for GetUsageParamsMetric.
const (
	GetUsageParamsMetricCompute GetUsageParamsMetric = "compute"
	GetUsageParamsMetricMemory  GetUsageParamsMetric = "memory"
	GetUsageParamsMetricStorage GetUsageParamsMetric = "storage"
)

// Valid indicates whether the value is a known member of the GetUsageParamsMetric enum.
func (e GetUsageParamsMetric) Valid() bool {
	switch e {
	case GetUsageParamsMetricCompute:
		return true
	case GetUsageParamsMetricMemory:
		return true
	case GetUsageParamsMetricStorage:
		return true
	default:
		return false
	}
}

// CostInstance A cost visibility instance backed by Koku
type CostInstance struct {
	// ClusterId Resolved OpenShift cluster ID (from ClusterVersion)
	ClusterId *string `json:"cluster_id,omitempty"`

	// CreateTime Creation timestamp
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id DCM-level resource identifier.
	Id *string `json:"id,omitempty"`

	// Path Resource path
	Path *string `json:"path,omitempty"`

	// Spec Cost instance specification
	Spec CostSpec `json:"spec"`

	// Status Current status
	Status *CostInstanceStatus `json:"status,omitempty"`

	// StatusMessage Human-readable status message
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Last update timestamp
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// CostInstanceStatus Current status
type CostInstanceStatus string

// CostInstanceList Paginated list of cost instances
type CostInstanceList struct {
	Instances *[]CostInstance `json:"instances,omitempty"`

	// NextPageToken Token for next page
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// CostMetadata Resource metadata
type CostMetadata struct {
	// Labels Key-value labels
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Human-readable name
	Name string `json:"name"`
}

// CostModelSpec Cost model configuration
type CostModelSpec struct {
	// Distribution Overhead distribution strategy
	Distribution *CostModelSpecDistribution `json:"distribution,omitempty"`

	// Markup Markup percentage
	Markup *Markup `json:"markup,omitempty"`

	// Rates Rate definitions (omit for Tier 2 distribution-only)
	Rates *[]Rate `json:"rates,omitempty"`
}

// CostModelSpecDistribution Overhead distribution strategy
type CostModelSpecDistribution string

// CostSpec Cost instance specification
type CostSpec struct {
	// CostModel Cost model configuration
	CostModel *CostModelSpec `json:"cost_model,omitempty"`

	// Currency ISO 4217 currency code
	Currency *string `json:"currency,omitempty"`

	// Metadata Resource metadata
	Metadata CostMetadata `json:"metadata"`

	// ServiceType Must be "cost"
	ServiceType CostSpecServiceType `json:"service_type"`

	// Target Reference to the target resource
	Target CostTarget `json:"target"`
}

// CostSpecServiceType Must be "cost"
type CostSpecServiceType string

// CostTarget Reference to the target resource
type CostTarget struct {
	// ResourceId DCM cluster instance ID
	ResourceId string `json:"resource_id"`

	// ResourceType Target resource type
	ResourceType *string `json:"resource_type,omitempty"`
}

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string   `json:"detail,omitempty"`
	Instance *string   `json:"instance,omitempty"`
	Status   *int32    `json:"status,omitempty"`
	Title    string    `json:"title"`
	Type     ErrorType `json:"type"`
}

// ErrorType defines model for Error.Type.
type ErrorType string

// Health Health status singleton
type Health struct {
	Path    *string `json:"path,omitempty"`
	Status  *string `json:"status,omitempty"`
	Type    *string `json:"type,omitempty"`
	Uptime  *int    `json:"uptime,omitempty"`
	Version *string `json:"version,omitempty"`
}

// Markup Markup percentage
type Markup struct {
	Unit MarkupUnit `json:"unit"`

	// Value Markup value
	Value float64 `json:"value"`
}

// MarkupUnit defines model for Markup.Unit.
type MarkupUnit string

// Rate A single cost rate
type Rate struct {
	// CostType Cost classification
	CostType *RateCostType `json:"cost_type,omitempty"`

	// Metric Koku-compatible metric name
	Metric RateMetric `json:"metric"`

	// Value Rate value
	Value float64 `json:"value"`
}

// RateCostType Cost classification
type RateCostType string

// RateMetric Koku-compatible metric name
type RateMetric string

// InstanceIdPath defines model for InstanceIdPath.
type InstanceIdPath = string

// ListInstancesParams defines parameters for ListInstances.
type ListInstancesParams struct {
	// PageToken Token for fetching the next page of results
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// MaxPageSize Maximum number of results to return per page
	MaxPageSize *int32 `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
}

// CreateInstanceParams defines parameters for CreateInstance.
type CreateInstanceParams struct {
	// Id Client-assigned resource identifier (AEP-133). If omitted, the server generates a UUID.
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetCostReportParams defines parameters for GetCostReport.
type GetCostReportParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUsageParams defines parameters for GetUsage.
type GetUsageParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUsageParamsMetric defines parameters for GetUsage.
type GetUsageParamsMetric string

// CreateInstanceJSONRequestBody defines body for CreateInstance for application/json ContentType.
type CreateInstanceJSONRequestBody = CostInstance
